### ISSUE TITLE
Problemkarte 9 muss überarbeitet werden

### ISSUE THREAD

**Issue by alueck** [WOYM/documentation#8]
Problemkarte 9 enthält die Strategien von Problemkarte 8

**Comment by alueck** [comment]
Es handelte sich dabei um eine falsche Anordnung der Problemkarten. Dennoch wünschenswert wären weitere Strategien und die Angabe, welche Strategie gewählt wird.

**Comment by JurSch** [comment]
wtf wo ist die beschreibung hin?
